language: cpp
compiler: g++

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq g++-4.8
    - sudo apt-get install binutils-gold
    - sudo apt-get install freeglut3 freeglut3-dev
    - export CXX="g++-4.8"

before_script:
    - cd src

script:
    - make 
    - make ofast

notifications:
    email:
        - parth.kolekar@students.iiit.ac.in
